### ISSUE TITLE
Using stochrsi indicator

### ISSUE THREAD

**Issue by c0nf1ck** [Grademark/grademark#4]
There's a way to backtest using more complexes indicators?

I'm trying to figure out how to backtest using stochrsi and others indicators, but no idea till now

**Comment by ashleydavis** [comment]
Thanks for your feedback.

Grademark doesn't have any built-in indicators at all.

All indicators must be provided by the user. That means you can use whatever indicators you like, simple or complex.

In the Grademark first example I use a simple moving average that is provided by the data-forge-indicators library:

https://grademark.github.io/grademark-first-example/

If you'd like to know how that indicator is created and get some ideas for creating your own, please read the code for data-forge-indicators here:

https://github.com/data-forge/data-forge-indicators
