### ISSUE TITLE
Only minute bar data close and using multiple symbols in the CSV.

### ISSUE THREAD

**Issue by realBlueVein** [Grademark/grademark#5]
Hello! This is a VERY cool and lightweight library I am excited to learn more about. I am working on developing a backtesting solution that involves only the close of the equity price on minute bars and buys the equity on a spread difference. Thus the data looks like this:

Minute bar data.

Equity 1

YYYY-MM-DD HH:Mmm | price

Equity 2

YYYY-MM-DD HH:Mmm | price

I am trying to make a simple backtest that says if the spread is > x% then buy.

How does this system define what it is determining what to buy when you enter a new position? And with what size? How would I go about having two equities in there and then having it buy or sell that asset based on the spread? Cheers.

**Comment by realBlueVein** [comment]
So what I did to fix this just modified the CSV files and combine them into 1 file, just make the OHL the same as the close, and then import the spread like any other indicator. Seems to be working now.

**Comment by ashleydavis** [comment]
Cool, thanks for letting me know and for your feedback.

If you like Grademark, please remember to star this repository.
