### ISSUE TITLE
five bars

### ISSUE THREAD

**Issue by shulemmosko** [Grademark/grademark#8]
Hi, thank you for your work.
I'm about to test Grademark in my login I'm going to need to have access to the last five bars, how do I achieve it?

**Comment by ashleydavis** [comment]
Set the `lookbackPeriod` field of your strategy to `5` and then access the `lookback` field of the `args` object (it's a Data-Forge dataframe).

Like this:

```javascript
const strategy = {
        lookback: 5,

        entryRule: (enterPosition, args) => {
           const lookback = args.lookback;

           if (have_buy_signal) {
                enterPosition();
            }
        },

        exitRule: (exitPosition, args) => {
            if (have_sell_signal) {
                exitPosition(); 
            }
        },
    };
```
